version: "3.9"

services:
  server:
    container_name: "server"
    build: "./server"
    volumes:
      - ./server/:/app:delegated
    env_file: ./server/.env
    ports:
      - "8000:8000"
    command: uvicorn --port 8000 --host 0.0.0.0 main:app --reload

